package in.junctiontech.homeonline;

/**
 * Created by JUNCTION TECH on 8/27/2015.
 */
public interface DBConstant {

    public static final String LIVINGROOM_ID="livingRoomID",
    APPOINTMENT_ID="appointmentID",
    LIVINGROOM_SOFA="sofa",
    LIVINGROOM_DINNING_TABLE="dinningTable",
    LIVINGROOM_AC="ac",
    LIVINGROOM_TV="tv",
    LIVINGROOM_SHOERACK="shoeRack",
    LIVINGROOM_FLOORING_TYPE="flooringType",
    LIVINGROOM_FALSE_CEILING="falseCeiling",

    BEDROOM_ID="bedroomID",
    BEDROOM_BED="bed",
    BEDROOM_AC="ac",
    BEDROOM_TV="tv",
    BEDROOM_DRESSING_TABLE="dressingTable",
    BEDROOM_WARDROBE="wardrobe",
    BEDROOM_WINDOW="window",
    BEDROOM_ATTACHED_BALCONY="attachedBalconey",
    BEDROOM_ATTACHED_BATHROOM="attachedBathroom",
    BEDROOM_FLOORING_TYPE="flooringType",
    BEDROOM_FALSE_CEILING="falseCeiling",

    TOILET_ID="toiletID",
    TYPE="type",
    STYLE="style",
    HOT_WATER_SUPPLY="hotWaterSupply",
    GLASS_PARTITION="glassPartition",
    SHOWER_PARTITION="showerPartition",
    BATH_TUB="bathTub",
    BATHROOM_CABINATE="cabinate",
    WINDOW="window",
    EXHAUST_FAN="exhaustFan",
    BATHROOM_FLOORING_TYPE="flooringType",

    KITCHEN_ID="kitchenID",
    KITCHEN_CABINATE="cabinet",
    GAS_PIPELINE="gaspipLine",
    REFRIDGERATOR="refrigerator",
    WATER_PURIFIER="waterPurifier",
    MICROWAVE="microwave",
    LOFT="loft",
    PLATEFORM_MATERIAL="plateformMaterial",
    CHIMNEY_EXHAUST="chimneyExhaust",

    WASHDRY_ID="washdryID",
    WASHING_MACHINE="washingMachine",
    WASHDRY_FLOORING_TYPE="flooringType",

    IMAGE_ID="imageId",
    IMAGE_ROOM_ID="room_id",
    IMAGE="image",
    MEDIUM_IMAGES="medium_images",
    THUM_IMAGES="thum_images",

    APPOINTMENT_ADDRESS="address",
    APPOINTMENT_DATE="appointmentDate",
    NOTE="note",
    APPOINTMENT_STATUS="appointmentStatus",
    START_TIME="stratTime",
    END_TIME="endTime",

    APPDETAIL_ID="appdetailID",
    GEOLATITUDE="geoLatitude",
    GEOLONGITUDE="geoLongitude",
    USER_ID="userID",
    PROPERTY_TYPE="propertyType",
    BHK_TYPE="bhkType",
    PASSESSION_TIME="passessionTime",
    READY_TO_MOVE="readyToMove",
    PETS_ALLOWED="petsAllowed",
    APPOINTMENT_FOOD="apointmentFood",
    LEASE_TYPE="leaseType",
    PREFERRED_VISIT_TIME="preferredVisitTime",
    ADVERTISER_TYPE="advertiserType",
    LIVES_IN_BUILDING="livesinBuilding",
    NAME="name",
    PHONE="phone",
    APPOINTMENT_ALTER_PHONE="appointmentAlterPhone",
    APPOINTMENT_EMAIL="appointmentEmail",
    OWNER_TYPE="ownerType",
    DEVELOPER_TYPE="developerType",
    DEVELOPER_NAME="developerName",
    ADD_BUILDING_NO="addBuildingNO",
    BUILDING_NAME="buildingName",
    FLATE_NO="flatNO",
    FLOOR_NO="floorNum",
    APPOINTMENT_WING="apointmentWing",
    APPOINTMENT_STREET="apponitmentStreet",
    LOCALITY="locality",
    SUB_LOCALITY="subLocality",
    PINCODE="pincode",
    LANDMARK="landmark",
    RENT_AMOUNT="rentAmount",
    SECURITY_DEPOSITE="securityDeposit",
    BROKERAGE_FEE="brokarageFee",
    RENT_NEGOTIABLE="rentNegotiable",
    SECURITY_NEGOTIABLE="securityNegotiable",
    MAINTANANCE_FEE="maintainenceFee",
    NO_OF_FLOORS="noOfFloors",
    APPOINTMENT_TERRACE="appointmentTarrece",
    TERRACE_GARDEN="tarreceGarden",
    NO_OF_LIFTS="numOfLifts",
    APPOINTMENT_LIFT_TYPE="appointmentLiftType",
    BUILDING_AGE="buildingAge",
    APPOINTMENT_AREA_UOM="appointmentAreaUom",
    BUILT_UP_AREA="builtupArea",
    CARPET_AREA="carpetArea",
    NO_OF_STORYS="numOfStory",
    SERVENT_ROOM="serventRoom",
    PRAYER_ROOM="prayerRoom",
    BALCONY="balcony",
    TERRACE_ACCESS="terraceAccess",
    PRIVATE_ACCESS="privateTerrace",
    MAIN_ENTERANCE_FACING="mainEnterenceFacing",
    VISITOR_PARKING="visitorParking",
    PARKING="parkingAvail",
    PARKING_TYPE="parkingType",
    POWER_BACKUP="powerBackup",
    WI_FI_INTERNET="wifiInternet",
    NO_OF_APART_ON_FLOOR="noOfApartOnFloor",
    WATER_SUPPLY="waterSupply",
    SOLAR_WATER_HEATER="solarWaterHeater",
    GATED_COMMUNITY="gatedCommunity",
    REGISTERED_SOCIETY="registeredSociety",
    SOCIETY_NAME="SocietyName",
    NO_OF_BUILDING="noOfBuilding",
    SOCIETY_OVERHEAD_TANK="societyOverheadTank",
    BOUNDRY_FANCING_TYPE="boundryFencingType",
    CCTV_SERVILLANCE="cctvSurvelance",
    SMOKE_DETECTOR="smokeDetector",
    FIRE_HYDRANT_SYSTEM="fireHyderantSystem",
    SECURITY="security",
    CLUB_HOUSE="clubHouse",
    SWIMING_POOL="swimmingPool",
    GYM="gym",
    MULTI_PURPOSE_HALL="multipurposHall",
    BADMINTON_COURT="badmintonCourt",
    CAROM="carom",
    BASKETBALL_COURT="basketballCourt",
    VOLLEYBALL_COURT="volleyballCourt",
    TENNIS_COURT="tennisCourt",
    BILLIARDS_TABLE="billiardsTable",
    KIDS_PLAY_AREA="kidsPlayArea",
    SQUASH_COURT="squashCourt",
    YOGA_ROOM="yogaRoom",
    TABLE_TENNIS="tableTennis",
    GARDEN_LAWN="gardenLawn",
    SAUNNA_STEAM="saunaSteam",
    NO_OF_BATHROOM="numOfToilet",

    NO_OF_WASHDRY="numberofwashdry",
    NO_OF_KITCHEN="numofKitchens",
    NO_OF_LIVING_ROOM="numOfLivingRooms",
    NO_OF_BEDROOM="numOfBedrooms";


}
